<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add to cart1</name>
   <tag></tag>
   <elementGuidId>165187b3-2bbb-4e0d-8535-90a5f48ad7b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.sc-124al1g-0.jCsgpZ</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/main/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e586625f-bb7b-47d4-882a-16365211c018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>5528ea35-ca08-41ea-a562-4a6e4c7520ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-124al1g-0 jCsgpZ</value>
      <webElementGuid>ef03bb5b-0fd3-4a23-9230-c93f5cd65240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add to cart</value>
      <webElementGuid>7cf0afe1-5f21-46db-a6bc-0a7de9233e75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-ebmerl-0 foenKb&quot;]/main[@class=&quot;sc-ebmerl-1 bmmyxu&quot;]/main[@class=&quot;sc-ebmerl-3 hewZDo&quot;]/div[@class=&quot;sc-uhudcz-0 iZZGui&quot;]/div[@class=&quot;sc-124al1g-2 dwOYCh&quot;]/button[@class=&quot;sc-124al1g-0 jCsgpZ&quot;]</value>
      <webElementGuid>56b595ca-4c86-43a9-8f2b-5abb2dc45057</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/main/div/div/button</value>
      <webElementGuid>fed20e0e-0d72-4a89-9679-b1d1861b6bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$1.21'])[1]/following::button[1]</value>
      <webElementGuid>e30be1c5-b618-461c-9554-e00a434b9965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Free shipping'])[2]/preceding::button[1]</value>
      <webElementGuid>2ba9f8c4-e375-4876-9a5c-1e4579c876f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$'])[2]/preceding::button[1]</value>
      <webElementGuid>7b0db8da-d7f9-408e-974b-fbcb62f9dcc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add to cart']/parent::*</value>
      <webElementGuid>d497ec2b-d866-4ba6-9673-1cc071f1645e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>4fb96581-0e7b-44d0-a0e2-607b98777ebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Add to cart' or . = 'Add to cart')]</value>
      <webElementGuid>bfdbb018-dee4-452d-83b7-c4faeac6a554</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
